#ifndef ARKHORSCRIPT_GLOBAL_H
#define ARKHORSCRIPT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ARKHORSCRIPT_LIBRARY)
#  define ARKHORSCRIPTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ARKHORSCRIPTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ARKHORSCRIPT_GLOBAL_H
