#ifndef ARKHORCLIENTSTATICRES_GLOBAL_H
#define ARKHORCLIENTSTATICRES_GLOBAL_H

#include <QtGlobal>

#undef ARKHOR_CLIENTSTATICRES_EXPORTING
#undef ARKHOR_CLIENTSTATICRES_IMPORTING

#ifdef Q_OS_WIN32
#   ifdef ARKHOR_CLIENTSTATICRES_DLL
#       define ARKHOR_CLIENTSTATICRES_EXPORTS __declspec(dllexport)
#       define ARKHOR_CLIENTSTATICRES_EXPORTING
#   else
#       define ARKHOR_CLIENTSTATICRES_EXPORTS __declspec(dllimport)
#       define ARKHOR_CLIENTSTATICRES_IMPORTING
#   endif
#else
#   define ARKHOR_CLIENTSTATICRES_EXPORTS
#endif


#endif // ARKHORCLIENTSTATICRES_GLOBAL_H
